### ISSUE TITLE
Unable to find plugin on pub.dev

### ISSUE THREAD

**Issue by rakhimian** [nk2IsHere/tinkoff_acquiring_sdk_flutter#1]
Hi! Can you deploy code as a package on pub.dev? Thanks!

**Comment by nk2IsHere** [comment]
Hi! I am thinking about publishing it onto pub.dev, though Im unable to make docs and other pub.dev essential things (like readme.md) right now.
I will see if I can get myself some time to do this

**Comment by rakhimian** [comment]
Thanks a lot! I found your example from GitHub quite clear. So you can publish it to use asa well as edit Readme file but later.

**Comment by nk2IsHere** [comment]
Up here: [https://pub.dev/packages/tinkoff_acquiring_sdk](https://pub.dev/packages/tinkoff_acquiring_sdk)

**Comment by rakhimian** [comment]
I'll check it as soon as. Thanks
